### ISSUE TITLE
PheMAP files not exist

### ISSUE THREAD

**Issue by LinglongQian** [mims-harvard/ClinVec#1]
Code in [kg/construct_kg.ipynb](https://github.com/mims-harvard/Clinical-knowledge-embeddings/blob/main/kg/construct_kg.ipynb) got `ERROR 404: Not Found.`
Can't find the file when downloading from the [website](https://www.vumc.org/cpm/phemap) as well.
Not sure if the data can be shared as well.

```
!wget https://phewascatalog.org/files/phemap/PheMap_Mapped_Terminologies_1.1.csv
!wget https://phewascatalog.org/files/phemap/Phecode_Relationship.csv 

!wget https://phewascatalog.org/files/phecode_definitions1.1.csv.zip 
!unzip phecode_definitions1.1.csv.zip

!wget https://phewascatalog.org/files/phecode_icd9_map_unrolled.csv.zip
!unzip phecode_icd9_map_unrolled.csv.zip
```

**Comment by ruthjohnson95** [comment]
Hi @LinglongQian, thank you for bringing this to our attention. We've added local versions of the files under "kg/phemap/" to address this error. We note that PheMap is under a Creative Commons Attribution-NonCommercial-NoDerivs license, permitting the non-commercial redistribution.

**Comment by LinglongQian** [comment]
Hi @ruthjohnson95 ,

Thank you for the prompt response and for adding the local versions of the PheMAP files. I'll use the updated files for my work and let you know if I encounter any further issues.

Best regards,
Linglong
