### ISSUE TITLE
License

### ISSUE THREAD

**Issue by andrewwarrington** [mims-harvard/ClinVec#2]
Hello!  This is super exciting work, super excited to dig into it!  Are you able to add a license to this repository so that we can correctly use/attribute the repository?  Thanks, andy!  :)

**Comment by ruthjohnson95** [comment]
Thank you for bringing this to our attention. I've added the licensing information in the main folder. Enjoy!

**Comment by andrewwarrington** [comment]
Thank you very much! 😄
